# Generated by Django 4.2 on 2023-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items_List",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(default="my_default_value")),
                ("imgs", models.ImageField(upload_to="images/")),
            ],
            options={
                "db_table": "Items_List",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserScore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nickname",
                    models.CharField(default="my_default_value", max_length=50),
                ),
                ("score", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "UserScore",
                "managed": True,
            },
        ),
    ]
