# Generated by Django 4.2 on 2023-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("score", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "User",
                "managed": False,
            },
        ),
    ]
