# Generated by Django 4.2 on 2023-04-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserScore",
            fields=[
                (
                    "nickname",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("score", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "UserScore",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
