# Generated by Django 4.2 on 2023-04-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_userscore_delete_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userscore",
            options={},
        ),
        migrations.AlterModelTable(
            name="userscore",
            table=None,
        ),
    ]
