# Generated by Django 4.2 on 2023-04-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_userscore_options_alter_userscore_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="items_list",
            options={},
        ),
    ]
