# Generated by Django 4.2 on 2023-04-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_alter_items_list_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="items_list",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="userscore",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="userscore",
            table="UserScore",
        ),
    ]
